permissionset 50001 "E3 Indent Permission"
{
    Assignable = true;
    Caption = 'HIS Permission Sets', MaxLength = 30;
    Permissions = table "E3 Indent Header" = X,
    tabledata "E3 Indent Header" = RIMD,
    table "E3 Indent Line" = X,
    tabledata "E3 Indent Line" = RIMD,
    table "E3 Indenter Master" = X,
    tabledata "E3 Indenter Master" = RIMD,
    page "E3 Indent List" = X,
    page "E3 Indent Card" = X,
    page "E3 Indent Line Subform" = X,
    page "E3 Indenter Master List" = X,
    table "E3 Voucher Type" = X,
    tabledata "E3 Voucher Type" = RIMD,
    page "E3 Voucher Types" = X,
    table "E3 Item Make Master" = X,
    tabledata "E3 Item Make Master" = RIMD,
    page "E3 Item Make Master" = X,
    table "E3 Indent Purchase Processing" = X,
    tabledata "E3 Indent Purchase Processing" = RIMD,
    Page "E3 Quotation Card" = X,
    page "E3 Approved Indent List" = X,
    page "E3 Approved HIS Indent List" = X,
    page "E3 Indent Purchase Processing" = X,
    page "E3 Quotation List" = X,
    table "E3 Indent Cue" = X,
    tabledata "E3 Indent Cue" = RIMD,
    page "E3 Indent Cue Card" = X,
    page "E3 Indent Role Center" = X,
    Page "E3 HIS Indent List" = X,
    Page "E3 HIS Indent Card" = X,
    page "E3 HIS Indent Line Subform" = X,
    table "E3 Rate Contract Header" = X,
    tabledata "E3 Rate Contract Header" = RIMD,
    table "E3 Rate Contract Line" = X,
    tabledata "E3 Rate Contract Line" = RIMD,
    page "E3 Rate Contract List" = X,
    page "E3 Rate Contract Card" = X,
    page "E3 Rate Contract Subpage" = X,
    table "E3 RC Discount Header" = X,
    tabledata "E3 RC Discount Header" = RIMD,
    table "E3 RC Discount Line" = X,
    tabledata "E3 RC Discount Line" = RIMD,
    page "E3 RC Discount List" = X,
    page "E3 RC Discount Card" = X,
    page "E3 RC Discount Subpage" = X,
    page "E3 App. Rate Contract List" = X,
    page "E3 App. Rate Contract Card" = X,
    page "E3 App. Rate Contract Subpage" = X,
    page "E3 App. RC Discount List" = X,
    page "E3 App. RC Discount Card" = X,
    page "E3 App. RC Discount Subpage" = X;


}